import type { Metadata } from "next";
import { Exo} from "next/font/google";
import "./globals.css";
import Navbar from "./-component/Navbar/Navbar";
import Footer from "./-component/Footer/Footer";
import { Toaster } from "@/components/ui/toast"
import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button"
import FirstNav from "./-component/firstNav/FirstNav";
import { Weight } from "lucide-react";
import MyProvider from "./-component/myProvider/MyProvider";
import Providers from "./-component/TanStackProvider/TanStackProvider";




const Exofont = Exo({
  variable: "--font-Exo",
  subsets:['latin'],
  weight:['100','400' ,'700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${Exofont.className} antialiased`}
    >
      <body>
        <Providers>
        <MyProvider>
          
        <FirstNav/>
        <Navbar/>
        {children}
        
          <Toaster />


        <Footer/>
        </MyProvider>
        </Providers>
      </body>
    </html>
  );
}
